"""Bundle rendered candidate scenes and read-only evidence into a local review page."""
import argparse,base64,json,hashlib
from pathlib import Path
import cv2
import numpy as np
from PIL import Image,ImageDraw,ImageFont

p=argparse.ArgumentParser(description=__doc__)
p.add_argument('--preview',type=Path,required=True);p.add_argument('--capture',type=Path,required=True)
a=p.parse_args();out=a.preview;report=json.loads((out/'report.json').read_text())
meta=json.loads((a.capture/'cameras.json').read_text())['result']['cameras']['oak']
K=np.array(meta['intrinsics']);D=np.array(meta['distortion_coefficients'])
real=cv2.imread(str(a.capture/'cameras-oak-1944301091DA1C2E00.jpg'))
cv2.imwrite(str(out/'real-head-rectified.jpg'),cv2.undistort(real,K,D,None,K))
def uri(p):return 'data:image/jpeg;base64,'+base64.b64encode(p.read_bytes()).decode()
views=['overall','work','plan','profile','camera-detail','head','left-wrist','right-wrist']
images={c['name']:{v:uri(out/c['name']/(v+'.jpg')) for v in views} for c in report['cases']}
evidence={k:uri(p) for k,p in [('phone',a.capture/'cameras-phone_overview.jpg'),('head',out/'real-head-rectified.jpg')]}
rows=''.join(f"<tr><td>{c['base_line_setback_mm']:.0f} mm</td><td>{c['shoulder_pan_setback_mm']:.1f} mm</td><td>{c['initial']['camera_to_carton_min_mm']:.1f} mm</td><td>{c['sparse_pass_count']}/{c['probe_count']} sampled poses</td><td>NOT VALIDATED</td></tr>" for c in report['cases'])
html=r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Hoya Botto · final desk scene review</title>
<style>
:root{color-scheme:light;font:16px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#172c35;background:#f3f0e9}*{box-sizing:border-box}body{margin:0}header{background:#172c35;color:white;padding:26px 5vw 22px;border-bottom:5px solid #eb9a40}header p{margin:3px 0;color:#c8d3d6}h1{font-size:32px;margin:0 0 8px;letter-spacing:-1px}h2{font-size:21px;margin:0 0 10px}h3{font-size:17px;margin:0}main{max-width:1420px;margin:auto;padding:26px 4vw}small,.muted{color:#52656b}.tag{font-size:12px;font-weight:800;letter-spacing:1px}header .tag{color:#f5ba70}section{margin:0 0 24px}.facts{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.fact,.card{background:white;border:1px solid #d7dedf;border-radius:9px;padding:18px}.fact strong{display:block;font-size:26px}.notice{border-left:5px solid #c5802e;background:#fff6e5;padding:14px 18px;margin:18px 0}.viewer{display:grid;grid-template-columns:1fr 290px;gap:20px}.screen{background:#172c35;border-radius:8px;overflow:hidden;min-height:350px}.screen img{width:100%;display:block}.toolbar{display:flex;gap:7px;flex-wrap:wrap;margin:0 0 12px}button{background:#fff;border:1px solid #7a9099;border-radius:5px;padding:9px 12px;font:inherit;color:#172c35;cursor:pointer}button[aria-pressed=true]{background:#172c35;color:white;border:2px solid #172c35}button:focus-visible,textarea:focus{outline:3px solid #e58c30;outline-offset:2px}.setbacks button{width:100%;margin:5px 0;text-align:left}.spec{padding:9px 0;border-bottom:1px solid #e0e5e5}.spec b{float:right}.comparison{display:grid;grid-template-columns:1fr 1fr;gap:16px}.comparison img{width:100%;display:block;background:#172c35}.phone{max-height:400px;width:auto!important;margin:auto}.caption{font-size:14px;padding:10px 0}.notes{margin-top:14px}textarea{width:100%;min-height:88px;font:inherit;padding:10px;border:1px solid #9caaaf;border-radius:4px;background:#fffefb}table{border-collapse:collapse;width:100%;font-size:14px}th,td{padding:12px 10px;text-align:left;border-bottom:1px solid #d4dcdf}th{background:#e8eeef}.scroll{overflow:auto}details{margin-top:14px}summary{cursor:pointer;font-weight:700}footer{font-size:13px;color:#52656b;margin:22px 0}#copy-status{font-size:13px;margin-left:12px}@media(max-width:900px){.viewer{grid-template-columns:1fr}.facts{grid-template-columns:1fr 1fr}.comparison{grid-template-columns:1fr}h1{font-size:26px}}
</style><header><div class="tag">HOYA BOTTO / SCENE REVIEW / 09 OCT 2026</div><h1>The final desk, with camera bodies included.</h1><p>DCM-F5040H · local simulation preview · training has not started</p></header><main>
<section class="facts"><div class="fact"><small>TABLE HEIGHT · CONFIRMED</small><strong>700 mm</strong>Floor to tabletop</div><div class="fact"><small>TABLETOP · CONFIRMED</small><strong>500 × 480 mm</strong>Width × depth; rectangular · label capacity 5 kg</div><div class="fact"><small>CARTON · ESTABLISHED</small><strong>379 × 283 × 108</strong>Millimetres; 140 mm flaps</div><div class="fact"><small>WRIST CAMERA · CAD</small><strong>36 × 67 × 43 mm</strong>X × Y × Z; collisions enabled</div></section>
<div class="notice"><b>Review candidate — physical placement is not calibrated.</b> Table dimensions are confirmed by you. Mount height, base spacing, cart setback and carton placement are model assumptions. A camera match or a clear parked pose does not establish a safe folding path.</div>
<section><div class="toolbar" id="views"></div><div class="viewer"><div><div class="screen"><img id="scene" alt="Rendered candidate robot and desk"></div><p class="caption" id="caption"></p><div class="notes"><label for="view-note"><b>Notes on this view</b> · saved locally in this browser</label><textarea id="view-note" placeholder="What should change in this scene?"></textarea></div></div>
<aside class="card"><h2>Compare setback</h2><p class="muted">These are candidate dimensions, not measured current positions.</p><div class="setbacks" id="setbacks"></div><div class="spec">Pan-axis setback <b id="pan"></b></div><div class="spec">Camera gap at park <b id="gap"></b></div><div class="spec">Sparse poses passing <b id="passes"></b></div><p class="muted">The pan axis is 38.8 mm forward of the base mounting origin in this model.</p><h3>Placement assumptions</h3><p>220 mm base spacing<br>729.1 mm mount height above floor<br>10 mm carton inset from near edge<br>500 mm table edge across the robot</p><p class="muted">The desk legs and 32 mm thickness are schematic. Arm fabric, cables and camera-module mass are not calibrated. No wedge added.</p></aside></div></section>
<section class="card"><h2>Final configuration · fresh evidence</h2><p>Captured at 18:34:23 JST. All 16 motors reported released; encoder readings stayed unchanged. The phone’s foreground round surface is separate from the brown tabletop supporting the carton.</p><div class="comparison"><div><img class="phone" id="phone" alt="Fresh phone view of carton on rectangular desk beside robot"><p class="caption">Real phone view. It does not show the complete tabletop outline or establish millimetre offsets.</p></div><div><img id="real-head" alt="Rectified real OAK head view"><p class="caption">Real OAK view, rectified with all 14 factory distortion coefficients and the supplied intrinsic matrix.</p><img id="sim-head" alt="Simulated head view for selected setback"><p class="caption">Simulated OAK view at the selected setback. Exact 640 × 360 pinhole intrinsics; CAD lens location and conditional historical 35.145° tilt / −5.132° pan. The remaining framing mismatch is visible and unresolved.</p></div></div></section>
<section class="card"><h2>Clearance and reach screen</h2><div class="scroll"><table><thead><tr><th>Base-line setback</th><th>Pan-axis setback</th><th>Parked camera gap</th><th>Contact-pose screen</th><th>Full fold</th></tr></thead><tbody>__ROWS__</tbody></table></div><p><b>All three parked configurations clear the modeled carton.</b> None passes every sampled folding pose. Extra setback improves the parked gap; it does not yet have a validated folding approach.</p><details><summary>What was tested</summary><p>Eight terminal short-flap poses per station: left/right at 0°, 30°, 60°, 85°, nine deterministic IK starts each. The opposite arm stays parked. Gates: ≤8 mm position error, ≤10° face-normal error, ≥1 mm camera clearance and no forbidden penetration above 0.1 mm. Failures include camera/carton contact, arm self-contact and orientation error. Sparse static poses do not test transitions, loaded folding, friction or retention; they do not prove a station impossible.</p><p>Camera collision hulls are conservative convex hulls of the two upstream CAD parts per wrist. A solver test confirms the housing can push a free object; its visual-only counterpart applies no force. Static cart/table overlap is checked separately because fixed bodies do not generate normal contact entries.</p></details><div class="notes"><label for="review-note"><b>Overall review / next changes</b></label><textarea id="review-note" placeholder="Scene corrections, preferred setback, or measurements to add"></textarea></div></section>
<button id="copy">Copy all review notes</button><span id="copy-status" role="status"></span><footer>Prepared from local model assets and the server’s final-table handoff. No robot commands, training or deployment. All inputs and detailed probe results are alongside this page in report.json and per-candidate scene.xml files.</footer></main>
<script>
const images=__IMAGES__,evidence=__EVIDENCE__,cases=__CASES__;
const viewLabels={overall:'Overall',work:'Arms & carton',plan:'Top',profile:'Side', 'camera-detail':'Camera housing',head:'Head','left-wrist':'Left wrist','right-wrist':'Right wrist'};
const captions={overall:'Cart and head use upstream CAD. This is a clear static park pose, not a reconstruction of the captured arm pose.',work:'Both wrist cameras are present as visual meshes and physical collision hulls. Arm fabric is not modeled.',plan:'Centered carton: 60.5 mm nominal support margin on each side, 10 mm near inset and 187 mm rear margin. Table axis orientation still needs physical confirmation.',profile:'700 mm floor-to-table height. The 729.1 mm mounting plane comes from model frame alignment, not a ruler measurement.','camera-detail':'Isolated right end effector. Camera envelope extends 67 mm along gripper Y. Tags and surrounding geometry hidden only for this detail render.',head:'Rectified 16:9 OAK view using factory intrinsics. Extrinsics are conditional; no new arm-to-camera calibration is claimed.','left-wrist':'Model-derived lens; 90° vertical field of view remains an assumption. Park pose differs from current hardware.','right-wrist':'Model-derived lens; 90° vertical field of view remains an assumption. Park pose differs from current hardware.'};
let chosen='setback-180',view='overall'; const prefix='hoya-dcm-refit-20261009:';
function key(){return prefix+chosen+':'+view}function get(k){try{return localStorage.getItem(k)||''}catch{return ''}}function save(k,v){try{localStorage.setItem(k,v)}catch{document.getElementById('copy-status').textContent='Storage unavailable. Copy your notes before closing.'}}
function update(){const c=cases.find(c=>c.name===chosen);document.getElementById('scene').src=images[chosen][view];document.getElementById('scene').alt=viewLabels[view]+' at '+c.base_line_setback_mm+' mm base-line setback';document.getElementById('caption').textContent=captions[view];document.getElementById('sim-head').src=images[chosen].head;document.getElementById('pan').textContent=c.shoulder_pan_setback_mm.toFixed(1)+' mm';document.getElementById('gap').textContent=c.initial.camera_to_carton_min_mm.toFixed(1)+' mm';document.getElementById('passes').textContent=c.sparse_pass_count+'/'+c.probe_count;document.getElementById('view-note').value=get(key());document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===view));document.querySelectorAll('[data-case]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.case===chosen))}
for(const [k,v]of Object.entries(viewLabels)){const b=document.createElement('button');b.textContent=v;b.dataset.view=k;b.onclick=()=>{view=k;update()};document.getElementById('views').append(b)}
for(const c of cases){const b=document.createElement('button');b.dataset.case=c.name;b.textContent=(c.base_line_setback_mm===150?'Baseline':c.base_line_setback_mm===180?'+30 mm':'+50 mm')+' · '+c.base_line_setback_mm+' mm base-line';b.onclick=()=>{chosen=c.name;update()};document.getElementById('setbacks').append(b)}
document.getElementById('phone').src=evidence.phone;document.getElementById('real-head').src=evidence.head;
document.getElementById('view-note').oninput=e=>save(key(),e.target.value);const review=document.getElementById('review-note');review.value=get(prefix+'overall');review.oninput=e=>save(prefix+'overall',e.target.value);
document.getElementById('copy').onclick=async()=>{const notes=['Hoya Botto / DCM desk scene review'];for(const c of cases)for(const [k,label]of Object.entries(viewLabels)){const n=get(prefix+c.name+':'+k);if(n)notes.push(c.base_line_setback_mm+' mm / '+label+'\n'+n)}if(review.value)notes.push('Overall review\n'+review.value);try{await navigator.clipboard.writeText(notes.join('\n\n'));document.getElementById('copy-status').textContent='Review notes copied.'}catch{const a=document.createElement('textarea');a.value=notes.join('\n\n');document.body.append(a);a.select();document.execCommand('copy');a.remove();document.getElementById('copy-status').textContent='Review notes copied.'}};update();
</script></html>'''
compact=[{k:c[k] for k in ('name','base_line_setback_mm','shoulder_pan_setback_mm','initial','sparse_pass_count','probe_count')} for c in report['cases']]
for key,value in [('__ROWS__',rows),('__IMAGES__',json.dumps(images)),('__EVIDENCE__',json.dumps(evidence)),('__CASES__',json.dumps(compact))]:html=html.replace(key,value)
(out/'scene-review.html').write_text(html)
# Compact preview for the chat, keeping the complete local views in the page.
canvas=Image.new('RGB',(1200,940),'#f3f0e9');draw=ImageDraw.Draw(canvas)
font='/System/Library/Fonts/Helvetica.ttc'
draw.text((25,16),'FINAL DESK · SCENE PREVIEW',font=ImageFont.truetype(font,29),fill='#172c35')
draw.text((25,57),'DCM-F5040H  |  500 × 480 × 700 mm  |  +30 mm setback candidate',font=ImageFont.truetype(font,18),fill='#172c35')
im=Image.open(out/'setback-180/overall.jpg');im.thumbnail((920,700));canvas.paste(im,(10,90))
phone=Image.open(a.capture/'cameras-phone_overview.jpg');phone.thumbnail((250,650));canvas.paste(phone,(935,90))
draw.text((940,550),'REAL · 18:34 JST',font=ImageFont.truetype(font,16),fill='#172c35')
draw.text((25,813),'Wrist-camera collision bodies included.  62.5 mm camera/carton gap at static park.',font=ImageFont.truetype(font,21),fill='#172c35')
draw.text((25,850),'Model mounting height and placement remain uncalibrated. Folding path not validated.',font=ImageFont.truetype(font,20),fill='#172c35')
draw.text((25,889),'TRAINING ON HOLD FOR SCENE REVIEW',font=ImageFont.truetype(font,19),fill='#172c35')
canvas.save(out/'preview.jpg',quality=95)
files=[p for p in out.rglob('*') if p.is_file() and p.name!='artifact-hashes.json']
(out/'artifact-hashes.json').write_text(json.dumps({str(p.relative_to(out)):hashlib.sha256(p.read_bytes()).hexdigest() for p in files},indent=2)+'\n')
print(out/'scene-review.html')
